version: "3.9"

services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "80:80" 
    restart: always
    depends_on:
      - backend
    
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "81:81"
    networks:
      - appnet
    environment:
      - DB_HOST=rdshost
      - DB_USERNAME=admin
      - DB_PASSWORD=Cloud123
      - DB_PORT=3306
      - DB_NAME=react_node_app

networks:
  appnet:
    driver: bridge
